[package]
name = "vallen"
version = "0.1.0"
authors = ["Johan Backman <backman93@gmail.com>"]

[workspace]
members = [
    # "engine",
    "game",
    # "editor",
    # etc ...
]

[[bin]]
name = "vallen"
path = "game/src/main.rs"
